### ISSUE TITLE
Link to github typo

### ISSUE THREAD

**Issue by TotalLag** [domness/MapleStory-Boss-Timer#2]
Great tool.  Love it.  Just noticed the link isn't actually pointing to your repo :)

https://github.com/domness/MapleStory-Boss-Timer/blob/71f173b67e209ea05f965f5a6200dc3c6ff0cfb5/_layouts/default.html#L8

Should be:

`<span class="credits">Project maintained by <a href="{{ site.github.owner_url }}">{{ site.github.owner_name }}</a> at <a href='https://github.com/domness/MapleStory-Boss-Timer'>GitHub</a></span>`

**Comment by domness** [comment]
Thanks! Nice find 🙂 Should be sorted now.
